# Generated by Django 5.0.6 on 2025-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_owner_aadhar_number_owner_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
