# Generated by Django 5.0.6 on 2025-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_owner_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
