# Generated by Django 5.0.6 on 2025-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_remove_owner_aadhar_number_remove_owner_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
