# Generated by Django 5.0.6 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_owner_aadhar_number_owner_dob_owner_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
