# Generated by Django 3.2.5 on 2022-05-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('femail', models.CharField(default='', max_length=50)),
                ('fmob', models.CharField(default='', max_length=12)),
                ('fwa', models.CharField(default='', max_length=12)),
                ('fadd', models.CharField(default='', max_length=100)),
                ('fcity', models.CharField(default='', max_length=50)),
                ('fdesc', models.CharField(default='', max_length=500)),
                ('fimg', models.ImageField(default='college/Screenshot.png', upload_to='faculty/')),
                ('fstatus', models.CharField(blank=True, max_length=10)),
                ('fpass', models.CharField(default='12345', max_length=50)),
                ('brid', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='college.branch')),
                ('coid', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='college.course')),
            ],
        ),
    ]
