# Generated by Django 3.2.5 on 2022-05-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
        migrations.AddField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
    ]
