# Generated by Django 3.2.5 on 2022-05-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20220502_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='brid',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='coid',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
