# Generated by Django 3.2.5 on 2022-05-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='fid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='college.faculty'),
        ),
    ]
