# Generated by Django 3.2.5 on 2022-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_alter_subject_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='susem',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
