# Generated by Django 3.2.5 on 2022-05-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_subject_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ass_fc', models.FileField(default='college/Screenshot.png', upload_to='student/assignment/')),
                ('ass_st', models.FileField(default='college/Screenshot.png', upload_to='faculty/assignment/')),
                ('due', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.faculty')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.subject')),
            ],
        ),
    ]
