# Generated by Django 3.2.5 on 2022-05-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_alter_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='college.student'),
        ),
    ]
