# Generated by Django 3.2.5 on 2022-05-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_alter_assignment_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='ass_fc',
            new_name='fass',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='ass_st',
        ),
        migrations.CreateModel(
            name='Assignment_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sass', models.FileField(default='college/Screenshot.png', upload_to='faculty/assignment/')),
                ('description', models.TextField(default='-')),
                ('assid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.assignment')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
    ]
