# Generated by Django 3.2.5 on 2022-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20220503_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_sub',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
