# Generated by Django 5.0.6 on 2025-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_aadhar_number_employee_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_code_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
