# Generated by Django 5.0.6 on 2025-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_qr_code_employee_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
