# Generated by Django 5.0.6 on 2025-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
